# Generated by Django 4.0.1 on 2022-01-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='Имя пользователя')),
                ('role', models.CharField(max_length=64, verbose_name='Роль пользователя')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
            ],
        ),
    ]
