# Generated by Django 4.0.1 on 2022-01-18 06:10

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import perepis.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail адресс')),
                ('csrfmiddlewaretoken', models.CharField(default='a', max_length=250, verbose_name='CSRF токен')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(default='perepis/no_avatar.png', upload_to=perepis.models.user_directory_path, verbose_name='Аватарка')),
                ('role', models.CharField(default='Бомж', max_length=64, verbose_name='Образование')),
                ('age', models.PositiveIntegerField(default=16, verbose_name='Возраст')),
                ('city', models.CharField(default='Не указан', max_length=300)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perepis.profileuser')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Rewiews',
            },
        ),
    ]
