# Generated by Django 4.0.1 on 2022-01-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perepis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='hometown',
            field=models.CharField(default='Севастополь', max_length=100),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='phone_number',
            field=models.CharField(default='+7(999)000111', max_length=100),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='university',
            field=models.CharField(default='Севастопольский Государственный Университет', max_length=100),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='city',
            field=models.CharField(default='Севастополь', max_length=100),
        ),
    ]
