# Generated by Django 4.0.1 on 2022-01-16 08:25

from django.db import migrations, models
import perepis.models


class Migration(migrations.Migration):

    dependencies = [
        ('perepis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Rewiews'},
        ),
        migrations.AddField(
            model_name='reviews',
            name='avatar',
            field=models.ImageField(default='userprofile_avatars/no_avatar.png', upload_to=perepis.models.user_directory_path),
        ),
    ]
