# Generated by Django 4.0.1 on 2022-01-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perepis', '0002_profileuser_hometown_profileuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='child',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='educations_degrees',
            field=models.CharField(default='Нет', max_length=100),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='in_relationship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='sex',
            field=models.CharField(default='Муж', max_length=5),
        ),
    ]
