# Generated by Django 4.0.1 on 2022-01-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perepis', '0003_profileuser_child_profileuser_educations_degrees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='education',
            field=models.CharField(default='Нет', max_length=64),
        ),
    ]
