# Generated by Django 4.0.1 on 2022-01-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perepis', '0005_badge_alter_emailaddr_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='doctor_of_sciencr',
            new_name='doctor_of_science',
        ),
        migrations.AlterField(
            model_name='badge',
            name='sex',
            field=models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина')], default='male', max_length=8, verbose_name='Пол'),
        ),
    ]
