# Generated by Django 4.0.1 on 2022-01-17 13:20

from django.db import migrations, models
import perepis.models


class Migration(migrations.Migration):

    dependencies = [
        ('perepis', '0005_profileuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaddr',
            name='csrfmiddlewaretoken',
            field=models.CharField(default='a', max_length=250, verbose_name='CSRF токен'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='age',
            field=models.PositiveIntegerField(default=16, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='avatar',
            field=models.ImageField(default='perepis/no_avatar.png', upload_to=perepis.models.user_directory_path, verbose_name='Аватарка'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='city',
            field=models.CharField(choices=[(1, 'Sevastopole'), (2, 'Simferopole')], default='Не указан', max_length=300),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='role',
            field=models.CharField(default='Бомж', max_length=64, verbose_name='Образование'),
        ),
    ]
