# Generated by Django 4.0.1 on 2022-01-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perepis', '0006_emailaddr_csrfmiddlewaretoken_profileuser_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='city',
            field=models.CharField(choices=[('Sevastopole', 'Севастополь'), ('Simferopole', 'Симферополь')], default='Не указан', max_length=300),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='role',
            field=models.CharField(default='a', max_length=64, verbose_name='Роль пользователя'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='username',
            field=models.CharField(default='a', max_length=32, verbose_name='Имя пользователя'),
        ),
    ]
